### ISSUE TITLE
Corrupted UI layout in C64Studio 7.0.1

### ISSUE THREAD

**Issue by tingtron** [GeorgRottensteiner/C64Studio#57] opened 2022-01-12 00:09 UTC
After installing C64Studio 7.0.1, the UI layout is corrupted:
- No Solution Explorer
- No bottom panels (Issues, Log, etc)

Note: the old version 6.1 is still working fine, without such issues.

![C64Studio701_issues](https://user-images.githubusercontent.com/2383820/149040907-5b17c104-e95e-4cae-bf23-66c832b063ab.png)

**Comment by tingtron** [comment] 2022-01-12 00:25
When the `settings.dat` is removed, it looks fine. 
But then after settings are saved upon exit, when starting again, the issue is back again.
So maybe `settings.dat` get corrupted?

Note: this behavior is the same in "Normal" and "Portable" modes.

**Comment by GeorgRottensteiner** [comment] 2022-01-12 04:37
I couldn't reproduce this. Which OS are you using, which DPI setting?
Also, could you attach your settings.dat here once it's saved?

**Comment by tingtron** [comment] 2022-01-12 12:02
Windows 10 64-bit Pro 21H1 build 19043.1415.

Note: it would be useful to report the used .NET version in About box.
From the registry:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
    Version    REG_SZ    4.8.04084

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727\1033
    Version    REG_SZ    2.0.50727.4927
```

Usually these settings.dat are supposed to be in [Registry Hive](https://www.damirscorner.com/blog/posts/20150117-ManipulatingSettingsDatFileWithSettingsFromWindowsStoreApps.html) format. But it doesn't seem to be the case here.

```
c:>reg load HKLM\_Tmp .\settings.dat
ERROR: The system has attempted to load or restore a file into the registry, 
but the specified file is not in a registry file format.
```

**Comment by GeorgRottensteiner** [comment] 2022-01-12 12:12
Thanks! Settings.dat is a binary file with hierarchical chunks (similar to what 3dStudio did back then)

**Comment by tingtron** [comment] 2022-01-16 07:20
An update: the last couple of days, possibly after computer reboot, the issue cannot be reproduced.
So possibly it was environment related (file access/permissions/visibility etc related to ,NET) or
some race conditions between file access and UI.

**Comment by GeorgRottensteiner** [comment] 2022-01-16 07:40
Thanks for the update. I tried various things (changing DPI settings) etc, but couldn't reproduce on my side at all. If it's fine for you I'll close this; reopen if it shows up again.

**Closed by GeorgRottensteiner** 2022-01-16 07:40 UTC
