### ISSUE TITLE
Breaking at start address doesn't seem to be working as expected

### ISSUE THREAD

**Issue by fade0ff** [GeorgRottensteiner/C64Studio#28] opened 2019-12-09 20:48 UTC
When I set DebugStartAddress to 0xF000 for an UltiMax project, the Vice monitor breaks at the first instruction, but for some reason C64Studio doesn't get control. I have to continue using "g" in the monitor, bu then the program just keeps on running. From there on, I can break and single step in C64Studio, but this way it's impossible to debug the start of the program from C64Studio.

The start parameters look OKish:
`E:\emu\computer\c64\GTK3VICE-3.3-win32-r35872\x64sc.exe with -truedrive +virtualdev -initbreak 0xf000 -remotemonitor -moncommands "C:\Users\fade0ff\AppData\Local\Temp\tmpEE77.tmp" -cartcrt "E:\src\C64\Dead Test\Dead Test\dead_test_0xfade0ff.crt"`

**Comment by GeorgRottensteiner** [comment] 2019-12-10 06:52
Nice catch! This looks like a racing condition. VICE is running cart code before C64Studio manages to connect to the remote monitor. Once you're in VICE and connected, you can break with C64Studio (the pause symbol) and go from there. Obviously that's just a work around, I'll try to find a way to get into it from the start.

**Comment by GeorgRottensteiner** [comment] 2019-12-11 06:42
I've checked in an attempt, that seems to work mostly. You have to modify your tool command, remove the -initbreak $(DebugStartAddressHex) part of the debug argument.

Please let me know if it works fully as intended.

**Comment by fade0ff** [comment] 2019-12-11 18:23
I tried that solution and it doesn't break automatically anymore (i.e. no initbreak parameter and DebugStartAddress  is ignored). Is this intended? If so, it's a bit strange that the DebugStartAddress   can still be set and the initbreak parameter is displayed under tools but then ignored when debugging.

So I need to break, set a breakpoint manually at 0xf000, stop/restart debugging and then (the 2nd time), the debugger starts at the first instruction. I tried this with the previous version and there it wouldn't work. So this is definitely an improvement. Personally, I could live with this but if DebugStartAddress  and initbreak are deliberately ignored, wouldn't it make sense to remove them?

**Comment by GeorgRottensteiner** [comment] 2019-12-11 20:26
initbreak is not used for cartridges, I kept it for non carts though. The DebugStartAddress should be used, not via initbreak, but indirectly with the -moncommands file.
If it isn't, then that's a plain bug in my "solution".

Regarding setting a breakpoint at $f000, is that address used as jump vector in $fffc?
It could be that I need to attempt your exact constellation. Could you provide an as short as possible sample that exhibits the wonky behaviour?

**Comment by fade0ff** [comment] 2019-12-11 20:57
Yes, 0xf000 is used for the jump vector. The binary also works in a real cartridge.
Just as an example, not for anything else, a version of kinzi's Dead Test modification 004 with a very few changes to improve the LED blinking on the tape port:
[Dead Test.zip](https://github.com/GeorgRottensteiner/C64Studio/files/3952537/Dead.Test.zip)

**Comment by GeorgRottensteiner** [comment] 2019-12-12 06:30
Ah, I think I finally understand and found the cause. I've checked in a potential fix. The address configured as debug start address is now actually used as first intermediate break point, similar to "Run to cursor".

**Comment by fade0ff** [comment] 2019-12-12 17:20
Yep, this works for me. Great support as always. Thanks!

**Comment by GeorgRottensteiner** [comment] 2019-12-12 17:31
Goodie :)
Closing this then.

**Closed by GeorgRottensteiner** 2019-12-12 17:31 UTC
