### ISSUE TITLE
WeifenLuo.WinFormsUI.Docking.dll is out of date

### ISSUE THREAD

**Issue by tingtron** [GeorgRottensteiner/C64Studio#23] opened 2019-06-10 05:54 UTC
The assembly `WeifenLuo.WinFormsUI.Docking.dll` included in the source files is `2.9.0.0`.
Whereas the C64Studio.csproj references `3.0.4.0`.

During build the following error occurs:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not res
olve this reference. Could not locate the assembly "WeifenLuo.WinFormsUI.Docking, Version=3.0.4.0, Culture=neutral, Pub
licKeyToken=5cded1a1a0a7b481, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this refe
rence is required by your code, you may get compilation errors.
...
Considered "bin\Debug\WeifenLuo.WinFormsUI.Docking.dll", but its name "WeifenLuo.WinFormsUI.Docking, Version=
  2.9.0.0, Culture=neutral, PublicKeyToken=5cded1a1a0a7b481" didn't match.
```

**Comment by GeorgRottensteiner** [comment] 2019-06-10 05:59
I can't reproduce this one. 
Can you do a full rebuild and maybe also a restore packages up front?

**Comment by GeorgRottensteiner** [comment] 2019-09-10 03:48
Is that issue still happening?

**Comment by RUA71** [comment] 2019-11-01 12:17
For my understandig the upload #25 fixed the issue.

**Comment by GeorgRottensteiner** [comment] 2019-11-01 13:34
Great, I'm closing this then. Thanks!

**Closed by GeorgRottensteiner** 2019-11-01 13:34 UTC
